{include file='_head_landing.tpl'} {include file='_header.tpl'} {include
file='_navbar_landingpage.tpl'}
<!--headerends-->

<section class="social-media subPageWrap">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 col-sm-5 col-xs-12"></div>
      <div class="col-md-5 col-sm-6 col-xs-12">
        <div class="backMainpageWrap">
            <a href="{$system['system_url']}" class="backMianPage">
                <img src="{$system['system_url']}/content/themes/{$system['theme']}/images/landingPage//images/arrowReadmore.svg" alt="">
                <span>Back to the main page</span>
            </a>
        </div>
      </div>
      <div class="col-md-1 col-sm-1 col-xs-12"></div>
      <h2 class="main-heading monetizationSubHeading">
        Best Monetization <br />in Social Media
      </h2>
      <div class="socialMediaWrap">
        <div class="col-md-6 col-sm-6 col-xs-12 common-space">
          <div class="social-left-col">
            <img src="{$system['system_url']}/content/themes/{$system['theme']}/images/landingPage/images/Star.svg" alt="Star" />
            <h3>VIP Platform</h3>
            <p>
              The VIP platform will allow influencers to publish VIP content,
              such as live streams, videos, group chats and many others.
              Charging viewers a micro transaction that most viewers wouldn’t
              think twice about. This can increase income by as much as $1
              million USD per 1 Million views.
            </p>
          </div>
        </div>

        <div class="col-md-6 col-sm-6 col-xs-12 common-space">
          <div class="social-left-col">
            <img src="{$system['system_url']}/content/themes/{$system['theme']}/images/landingPage/images/donation.svg" alt="donation.svg" />
            <h3>One Click Donations</h3>
            <p>There will be micropayments on many posts and videos.</p>
          </div>
        </div>

        <div class="col-md-6 col-sm-6 col-xs-12 common-space store-bg">
          <div class="social-left-col">
            <img src="{$system['system_url']}/content/themes/{$system['theme']}/images/landingPage/images/commision.svg" alt="commision" />
            <h3>Instant Endorsement Commissions</h3>
            <p>
              The instant endorsement system works with our competitor for
              Amazon/EBay and allows any seller to offer instant endorsement
              opportunities to influencers on the system. <br />
              There will be a queue of products and services that influencers
              can select from to endorse, allowing them to make as much as 50%
              on any sales generated by their video. So you can make money from
              product reviews that you were going to do anyway, this benefits
              influencers and viewers because influencers are able to afford
              better content.
            </p>
          </div>
        </div>

        <div class="col-md-6 col-sm-6 col-xs-12 common-space store-bg">
          <div class="social-left-col">
            <img src="{$system['system_url']}/content/themes/{$system['theme']}/images/landingPage/images/speaker.png" alt="speaker" />
            <h3>Direct Advertising</h3>
            <p>
              Influencers are able to make much more on direct advertising than
              others, such as Youtube, and Stratus shares its advertising
              revenue with the biggest influencers on its platforms that are
              meant to replace Facebook, Twitter, Tik Tok, Instagram, medium and
              others. This means that influencers will eventually collect
              revenue indefinitely from ads shown on their pages. Because
              Stratus will offer one account access to an internet of services,
              ad revenue is increased substantially because sales happen with
              one click on the same platform, so customer acquisition is
              significantly higher.
            </p>
          </div>
        </div>

        <div class="col-md-6 col-sm-6 col-xs-12 common-space">
          <div class="social-left-col">
            <img src="{$system['system_url']}/content/themes/{$system['theme']}/images/landingPage/images/Shop.svg" alt="Shop" />
            <h3>Embed a Product Store</h3>
            <p>
              Influencers will be able to embed a product into a video allowing
              their subscribers to order the product with one click. This will
              show up as a button on the video itself and can be a product or
              service sold by the influencer directly, or a product placement
              from someone else. Because Stratus offers a one click payment
              wallet, like PayPal, payments in almost any currency are instant
              and easy. Users can also be taken to the influencer’s store after
              the video, significantly increasing cross-sales.
            </p>
          </div>
        </div>

        <div class="col-md-6 col-sm-6 col-xs-12 common-space">
          <div class="social-left-col">
            <img src="{$system['system_url']}/content/themes/{$system['theme']}/images/landingPage/images/refereal.svg" alt="refereal" />
            <h3>Referral Commissions</h3>
            <p>
              Indefinite referral commissions are given to influencers that
              suggest Stratus to their subscribers. Influencers will receive
              commissions on many of the services that their subscribers
              utilize, with commissions as high as 50% it’s not hard to see why
              Stratus is the only clear option for monetization.
            </p>
          </div>
        </div>
      </div>
      <!-- <div class="text-center mt-80 w-100">
                    <button class="learn-btn" type="button">Learn More</button>
                </div> -->
    </div>
  </div>
</section>

<div class="community-col">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-12 col-12">
          <div class="com-left">
            <h2 class="main-heading">A Huge <br>Community</h2>

            <h3 class="col-heading">What are you <br> waiting for?</h3>

            <button onclick="window.open('{$system['system_url']}/signup')" class="learn-btn mt-50 desktop-btn" type="button">Sign Up</button>
          </div>
        </div>
        <div class="col-md-6 col-sm-12 col-12 text-center">
          <img class="community" src="{$system['system_url']}/content/themes/{$system['theme']}/images/landingPage/images/community.png" alt="community">

          <button onclick="window.open('{$system['system_url']}/signup')" class="learn-btn mt-50 mobile-btn" type="button">Sign Up</button>
        </div>
      </div>
    </div>
  </div>

<!-- Get in touch -->
{include file='_getintouch.tpl'}

<!-- Footer Landing page -->
{include file='_footer_landingpage.tpl'}
